### ISSUE TITLE
Report the error：UnboundLocalError

### ISSUE THREAD

**Issue by SER1205** [hlz0606/SSPCM#2]
Hello, I report the error when running the program：
Traceback (most recent call last):
  File "pose_estimation/train.py", line 370, in <module>
    main()
  File "pose_estimation/train.py", line 306, in main
    final_output_dir, tb_log_dir, writer_dict, last_epoch_model)
  File "/SSPCM-main/SSPCM/pose_estimation/../lib/core/function.py", line 71, in train
    output = model(input, target_weight, optimizer, epoch, unsup_ht1_l, unsup_ht2_l)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/SSPCM-main/SSPCM/pose_estimation/../lib/models/my_pose_triple.py", line 592, in forward
    preds_ensemble, _ = get_max_preds_tensor(ensemble_unsup_ht.detach())
UnboundLocalError: local variable 'ensemble_unsup_ht' referenced before assignment

I will be very grateful if you can reply！

**Comment by KangqingYe** [comment]
Encountered the same error. Changed "if epoch > self.cfg.time_correction_warmup_epoch" to "if epoch >= self.cfg.time_correction_warmup_epoch".
